version = 0.1

[default.deploy.parameters]
stack_name = "sahil-resume-chatbot-stack"
s3_prefix = "sahil-resume-chatbot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
